const formNames = {
    'EDITUSERINFO': 'HGFHfFGH',
    'EDITSOCIAL': 'EDITUSERAVAfsdfTAR',
    'EDITDESCRIPTION': 'EDITUSEfsfsdRINFO',
    'EDITUSERBG': 'EDITDEfsffSCRIPTION',
    'EDITUSERAVATAR': 'EDITUSERAVATAR',
    'CHECKKEY': 'CHECKKEY',
    'EDITIMPORTANTINFO': 'EDITIMPORTANTINFO'
}
export default formNames;