const modalNames = {
    'EDITUSERBG': 'EDITUSERBG',
    'EDITUSERAVATAR': 'EDITUSERAVATAR',
    'EDITUSERINFO': 'EDITUSERINFO',
    'EDITDESCRIPTION': 'EDITDESCRIPTION',
    'EDITSOCIALS': 'EDITSOCIALS',
    'CHECKKEY': 'CHECKKEY',
    'EDITIMPORTANTINFO': 'EDITIMPORTANTINFO'
}

export default modalNames;